# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dpc.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(715, 925)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 10, 681, 861))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 10, 641, 111))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.groupBox_7)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 30, 612, 71))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.gridLayoutWidget_7)
        self.spinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_8.addWidget(self.spinBox, 1, 4, 1, 1)
        self.le_scan_num = QtGui.QLineEdit(self.gridLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_scan_num.sizePolicy().hasHeightForWidth())
        self.le_scan_num.setSizePolicy(sizePolicy)
        self.le_scan_num.setMaximumSize(QtCore.QSize(80, 16777215))
        self.le_scan_num.setObjectName(_fromUtf8("le_scan_num"))
        self.gridLayout_8.addWidget(self.le_scan_num, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_8.addWidget(self.pushButton, 1, 5, 1, 1)
        self.cb_detectorkind = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.cb_detectorkind.setObjectName(_fromUtf8("cb_detectorkind"))
        self.cb_detectorkind.addItem(_fromUtf8(""))
        self.cb_detectorkind.addItem(_fromUtf8(""))
        self.cb_detectorkind.addItem(_fromUtf8(""))
        self.cb_detectorkind.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cb_detectorkind, 1, 0, 1, 2)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_36.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_8.addWidget(self.label_36, 1, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 1, 2, 1, 1)
        self.cb_dataloader = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.cb_dataloader.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_dataloader.setObjectName(_fromUtf8("cb_dataloader"))
        self.cb_dataloader.addItem(_fromUtf8(""))
        self.cb_dataloader.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cb_dataloader, 0, 3, 1, 2)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 130, 641, 211))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.groupBox_8)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(19, 30, 601, 171))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_37 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_9.addWidget(self.label_37, 0, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_9.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_9.addWidget(self.label_42, 2, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_9.addWidget(self.label_38, 0, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_9.addWidget(self.label_40, 1, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_9.addWidget(self.label_41, 2, 0, 1, 1)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.gridLayout_9.addWidget(self.doubleSpinBox_7, 3, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget_8)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox, 4, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_9.addWidget(self.label_46, 4, 2, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_9.addWidget(self.doubleSpinBox_3, 1, 1, 1, 1)
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.gridLayout_9.addWidget(self.doubleSpinBox_8, 3, 3, 1, 1)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.gridLayout_9.addWidget(self.doubleSpinBox_6, 2, 3, 1, 1)
        self.label_44 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_9.addWidget(self.label_44, 3, 2, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.gridLayoutWidget_8)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_9.addWidget(self.spinBox_2, 4, 3, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_9.addWidget(self.doubleSpinBox_4, 1, 3, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_9.addWidget(self.label_39, 1, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_9.addWidget(self.doubleSpinBox_2, 0, 3, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_9.addWidget(self.doubleSpinBox_5, 2, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_9.addWidget(self.label_43, 3, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_9.addWidget(self.label_45, 4, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.groupBox_6)
        self.tabWidget.setGeometry(QtCore.QRect(20, 350, 641, 301))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(21, 11, 601, 241))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.sp_n_iterations = QtGui.QSpinBox(self.widget)
        self.sp_n_iterations.setMinimum(1)
        self.sp_n_iterations.setMaximum(999999)
        self.sp_n_iterations.setProperty("value", 50)
        self.sp_n_iterations.setObjectName(_fromUtf8("sp_n_iterations"))
        self.horizontalLayout_4.addWidget(self.sp_n_iterations)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.cb_alg_flag = QtGui.QComboBox(self.widget)
        self.cb_alg_flag.setObjectName(_fromUtf8("cb_alg_flag"))
        self.cb_alg_flag.addItem(_fromUtf8(""))
        self.cb_alg_flag.addItem(_fromUtf8(""))
        self.cb_alg_flag.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cb_alg_flag)
        self.cb_alg2_flag = QtGui.QComboBox(self.widget)
        self.cb_alg2_flag.setObjectName(_fromUtf8("cb_alg2_flag"))
        self.cb_alg2_flag.addItem(_fromUtf8(""))
        self.cb_alg2_flag.addItem(_fromUtf8(""))
        self.cb_alg2_flag.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cb_alg2_flag)
        self.sp_alg_percentage = QtGui.QDoubleSpinBox(self.widget)
        self.sp_alg_percentage.setProperty("value", 0.8)
        self.sp_alg_percentage.setObjectName(_fromUtf8("sp_alg_percentage"))
        self.horizontalLayout_4.addWidget(self.sp_alg_percentage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_10.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_10.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.widget)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_10.addWidget(self.checkBox, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_10.addWidget(self.label_11, 1, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.widget)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_10.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_10.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_10.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.ck_multislice_flag = QtGui.QCheckBox(self.widget)
        self.ck_multislice_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_multislice_flag.setObjectName(_fromUtf8("ck_multislice_flag"))
        self.gridLayout_11.addWidget(self.ck_multislice_flag, 1, 0, 1, 1)
        self.sp_slice_num = QtGui.QSpinBox(self.widget)
        self.sp_slice_num.setProperty("value", 2)
        self.sp_slice_num.setObjectName(_fromUtf8("sp_slice_num"))
        self.gridLayout_11.addWidget(self.sp_slice_num, 1, 3, 1, 1)
        self.label_47 = QtGui.QLabel(self.widget)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_11.addWidget(self.label_47, 1, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.widget)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_11.addWidget(self.label_48, 1, 4, 1, 1)
        self.sp_slice_spacing_m = QtGui.QDoubleSpinBox(self.widget)
        self.sp_slice_spacing_m.setProperty("value", 5.0)
        self.sp_slice_spacing_m.setObjectName(_fromUtf8("sp_slice_spacing_m"))
        self.gridLayout_11.addWidget(self.sp_slice_spacing_m, 1, 6, 1, 1)
        self.sp_prb_mode_num = QtGui.QSpinBox(self.widget)
        self.sp_prb_mode_num.setProperty("value", 5)
        self.sp_prb_mode_num.setObjectName(_fromUtf8("sp_prb_mode_num"))
        self.gridLayout_11.addWidget(self.sp_prb_mode_num, 0, 3, 1, 1)
        self.ck_save_tmp_pic_flag = QtGui.QCheckBox(self.widget)
        self.ck_save_tmp_pic_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_save_tmp_pic_flag.setObjectName(_fromUtf8("ck_save_tmp_pic_flag"))
        self.gridLayout_11.addWidget(self.ck_save_tmp_pic_flag, 0, 0, 1, 1)
        self.sp_obj_mode_num = QtGui.QSpinBox(self.widget)
        self.sp_obj_mode_num.setProperty("value", 1)
        self.sp_obj_mode_num.setObjectName(_fromUtf8("sp_obj_mode_num"))
        self.gridLayout_11.addWidget(self.sp_obj_mode_num, 0, 6, 1, 1)
        self.label_22 = QtGui.QLabel(self.widget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_11.addWidget(self.label_22, 0, 1, 1, 2)
        self.label_23 = QtGui.QLabel(self.widget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_11.addWidget(self.label_23, 0, 4, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.sp_amp_min = QtGui.QDoubleSpinBox(self.widget)
        self.sp_amp_min.setPrefix(_fromUtf8(""))
        self.sp_amp_min.setDecimals(3)
        self.sp_amp_min.setProperty("value", 0.85)
        self.sp_amp_min.setObjectName(_fromUtf8("sp_amp_min"))
        self.gridLayout_12.addWidget(self.sp_amp_min, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.widget)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_12.addWidget(self.label_33, 0, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.widget)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_12.addWidget(self.label_32, 0, 1, 1, 1)
        self.sp_amp_max = QtGui.QDoubleSpinBox(self.widget)
        self.sp_amp_max.setPrefix(_fromUtf8(""))
        self.sp_amp_max.setDecimals(3)
        self.sp_amp_max.setMinimum(-3.0)
        self.sp_amp_max.setProperty("value", 1.0)
        self.sp_amp_max.setObjectName(_fromUtf8("sp_amp_max"))
        self.gridLayout_12.addWidget(self.sp_amp_max, 0, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_12.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.widget)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_12.addWidget(self.label_34, 1, 1, 1, 1)
        self.sp_pha_min = QtGui.QDoubleSpinBox(self.widget)
        self.sp_pha_min.setPrefix(_fromUtf8(""))
        self.sp_pha_min.setDecimals(3)
        self.sp_pha_min.setMinimum(-99.0)
        self.sp_pha_min.setProperty("value", -0.6)
        self.sp_pha_min.setObjectName(_fromUtf8("sp_pha_min"))
        self.gridLayout_12.addWidget(self.sp_pha_min, 1, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.widget)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_12.addWidget(self.label_35, 1, 3, 1, 1)
        self.sp_pha_max = QtGui.QDoubleSpinBox(self.widget)
        self.sp_pha_max.setPrefix(_fromUtf8(""))
        self.sp_pha_max.setDecimals(3)
        self.sp_pha_max.setProperty("value", 0.01)
        self.sp_pha_max.setObjectName(_fromUtf8("sp_pha_max"))
        self.gridLayout_12.addWidget(self.sp_pha_max, 1, 4, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_12)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ck_gpu_flag = QtGui.QCheckBox(self.widget)
        self.ck_gpu_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_gpu_flag.setChecked(True)
        self.ck_gpu_flag.setObjectName(_fromUtf8("ck_gpu_flag"))
        self.horizontalLayout_5.addWidget(self.ck_gpu_flag)
        self.pushButton_4 = QtGui.QPushButton(self.widget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.widget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.widget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.widget)
        self.pushButton_7.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btn_recon_start = QtGui.QPushButton(self.widget)
        self.btn_recon_start.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_recon_start.setObjectName(_fromUtf8("btn_recon_start"))
        self.horizontalLayout_6.addWidget(self.btn_recon_start)
        self.btn_recon_stop = QtGui.QPushButton(self.widget)
        self.btn_recon_stop.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_recon_stop.setObjectName(_fromUtf8("btn_recon_stop"))
        self.horizontalLayout_6.addWidget(self.btn_recon_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.widget1 = QtGui.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(20, 10, 246, 41))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.sp_ccd_pixel_um = QtGui.QDoubleSpinBox(self.widget1)
        self.sp_ccd_pixel_um.setDecimals(3)
        self.sp_ccd_pixel_um.setProperty("value", 55.0)
        self.sp_ccd_pixel_um.setObjectName(_fromUtf8("sp_ccd_pixel_um"))
        self.horizontalLayout_2.addWidget(self.sp_ccd_pixel_um)
        self.widget2 = QtGui.QWidget(self.tab_2)
        self.widget2.setGeometry(QtCore.QRect(20, 60, 138, 41))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_31 = QtGui.QLabel(self.widget2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_3.addWidget(self.label_31)
        self.sp_processes = QtGui.QSpinBox(self.widget2)
        self.sp_processes.setObjectName(_fromUtf8("sp_processes"))
        self.horizontalLayout_3.addWidget(self.sp_processes)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 110, 27))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.le_sign = QtGui.QLineEdit(self.tab_2)
        self.le_sign.setGeometry(QtCore.QRect(140, 120, 150, 27))
        self.le_sign.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_sign.setObjectName(_fromUtf8("le_sign"))
        self.ck_p_flag = QtGui.QCheckBox(self.tab_2)
        self.ck_p_flag.setGeometry(QtCore.QRect(30, 160, 162, 22))
        self.ck_p_flag.setObjectName(_fromUtf8("ck_p_flag"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 200, 247, 27))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.sp_distance = QtGui.QDoubleSpinBox(self.tab_2)
        self.sp_distance.setGeometry(QtCore.QRect(120, 200, 101, 27))
        self.sp_distance.setDecimals(3)
        self.sp_distance.setMaximum(999999.999)
        self.sp_distance.setObjectName(_fromUtf8("sp_distance"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(330, 20, 31, 27))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cb_ml_mode = QtGui.QComboBox(self.tab_2)
        self.cb_ml_mode.setGeometry(QtCore.QRect(370, 10, 128, 27))
        self.cb_ml_mode.setObjectName(_fromUtf8("cb_ml_mode"))
        self.cb_ml_mode.addItem(_fromUtf8(""))
        self.label_30 = QtGui.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(330, 50, 127, 27))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.sp_dm_version = QtGui.QSpinBox(self.tab_2)
        self.sp_dm_version.setGeometry(QtCore.QRect(390, 50, 71, 27))
        self.sp_dm_version.setProperty("value", 1)
        self.sp_dm_version.setObjectName(_fromUtf8("sp_dm_version"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(340, 90, 128, 27))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.sp_alpha = QtGui.QDoubleSpinBox(self.tab_2)
        self.sp_alpha.setGeometry(QtCore.QRect(440, 90, 81, 27))
        self.sp_alpha.setDecimals(3)
        self.sp_alpha.setProperty("value", 1.0)
        self.sp_alpha.setObjectName(_fromUtf8("sp_alpha"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(340, 130, 71, 27))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.sp_beta = QtGui.QDoubleSpinBox(self.tab_2)
        self.sp_beta.setGeometry(QtCore.QRect(390, 130, 121, 27))
        self.sp_beta.setDecimals(3)
        self.sp_beta.setMaximum(96.99)
        self.sp_beta.setProperty("value", 0.9)
        self.sp_beta.setObjectName(_fromUtf8("sp_beta"))
        self.ck_init_obj_flag = QtGui.QCheckBox(self.tab_2)
        self.ck_init_obj_flag.setGeometry(QtCore.QRect(270, 180, 106, 22))
        self.ck_init_obj_flag.setChecked(True)
        self.ck_init_obj_flag.setObjectName(_fromUtf8("ck_init_obj_flag"))
        self.ck_init_obj_dpc_flag = QtGui.QCheckBox(self.tab_2)
        self.ck_init_obj_dpc_flag.setGeometry(QtCore.QRect(270, 210, 141, 22))
        self.ck_init_obj_dpc_flag.setObjectName(_fromUtf8("ck_init_obj_dpc_flag"))
        self.ck_init_prb_flag = QtGui.QCheckBox(self.tab_2)
        self.ck_init_prb_flag.setGeometry(QtCore.QRect(410, 180, 106, 22))
        self.ck_init_prb_flag.setObjectName(_fromUtf8("ck_init_prb_flag"))
        self.ck_mask_prb_flag = QtGui.QCheckBox(self.tab_2)
        self.ck_mask_prb_flag.setGeometry(QtCore.QRect(410, 210, 121, 22))
        self.ck_mask_prb_flag.setObjectName(_fromUtf8("ck_mask_prb_flag"))
        self.ck_prb_center_flag = QtGui.QCheckBox(self.tab_2)
        self.ck_prb_center_flag.setGeometry(QtCore.QRect(270, 240, 131, 22))
        self.ck_prb_center_flag.setChecked(True)
        self.ck_prb_center_flag.setObjectName(_fromUtf8("ck_prb_center_flag"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.ck_mesh_flag = QtGui.QCheckBox(self.tab_3)
        self.ck_mesh_flag.setGeometry(QtCore.QRect(40, 30, 67, 22))
        self.ck_mesh_flag.setChecked(True)
        self.ck_mesh_flag.setObjectName(_fromUtf8("ck_mesh_flag"))
        self.ck_cal_scal_pattern_flag = QtGui.QCheckBox(self.tab_3)
        self.ck_cal_scal_pattern_flag.setGeometry(QtCore.QRect(30, 60, 115, 22))
        self.ck_cal_scal_pattern_flag.setObjectName(_fromUtf8("ck_cal_scal_pattern_flag"))
        self.ck_sf_flag = QtGui.QCheckBox(self.tab_3)
        self.ck_sf_flag.setGeometry(QtCore.QRect(50, 100, 81, 22))
        self.ck_sf_flag.setObjectName(_fromUtf8("ck_sf_flag"))
        self.ck_ms_pie_flag = QtGui.QCheckBox(self.tab_3)
        self.ck_ms_pie_flag.setGeometry(QtCore.QRect(40, 140, 81, 22))
        self.ck_ms_pie_flag.setObjectName(_fromUtf8("ck_ms_pie_flag"))
        self.ck_weak_obj_flag = QtGui.QCheckBox(self.tab_3)
        self.ck_weak_obj_flag.setGeometry(QtCore.QRect(50, 180, 113, 22))
        self.ck_weak_obj_flag.setObjectName(_fromUtf8("ck_weak_obj_flag"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(170, 30, 89, 27))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.sp_start_ave = QtGui.QDoubleSpinBox(self.tab_3)
        self.sp_start_ave.setGeometry(QtCore.QRect(260, 30, 121, 27))
        self.sp_start_ave.setProperty("value", 0.8)
        self.sp_start_ave.setObjectName(_fromUtf8("sp_start_ave"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(190, 80, 41, 27))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.sp_nth = QtGui.QSpinBox(self.tab_3)
        self.sp_nth.setGeometry(QtCore.QRect(260, 80, 91, 27))
        self.sp_nth.setProperty("value", 5)
        self.sp_nth.setObjectName(_fromUtf8("sp_nth"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.widget3 = QtGui.QWidget(self.tab_4)
        self.widget3.setGeometry(QtCore.QRect(20, 10, 581, 141))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_12 = QtGui.QLabel(self.widget3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 0, 1, 1, 1)
        self.ck_bragg_flag = QtGui.QCheckBox(self.widget3)
        self.ck_bragg_flag.setObjectName(_fromUtf8("ck_bragg_flag"))
        self.gridLayout_5.addWidget(self.ck_bragg_flag, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.widget3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 1, 5, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 0, 3, 1, 1)
        self.sp_bragg_delta = QtGui.QDoubleSpinBox(self.widget3)
        self.sp_bragg_delta.setDecimals(3)
        self.sp_bragg_delta.setProperty("value", 15.46)
        self.sp_bragg_delta.setObjectName(_fromUtf8("sp_bragg_delta"))
        self.gridLayout_5.addWidget(self.sp_bragg_delta, 0, 6, 1, 1)
        self.sp_bragg_gamma = QtGui.QDoubleSpinBox(self.widget3)
        self.sp_bragg_gamma.setDecimals(3)
        self.sp_bragg_gamma.setProperty("value", 33.4)
        self.sp_bragg_gamma.setObjectName(_fromUtf8("sp_bragg_gamma"))
        self.gridLayout_5.addWidget(self.sp_bragg_gamma, 0, 4, 1, 1)
        self.sp_bragg_theta = QtGui.QDoubleSpinBox(self.widget3)
        self.sp_bragg_theta.setDecimals(3)
        self.sp_bragg_theta.setProperty("value", 69.41)
        self.sp_bragg_theta.setObjectName(_fromUtf8("sp_bragg_theta"))
        self.gridLayout_5.addWidget(self.sp_bragg_theta, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 5, 1, 1)
        self.ck_pc_flag = QtGui.QCheckBox(self.widget3)
        self.ck_pc_flag.setObjectName(_fromUtf8("ck_pc_flag"))
        self.gridLayout_5.addWidget(self.ck_pc_flag, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.widget3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 1, 1, 1, 1)
        self.sp_pc_sigma = QtGui.QDoubleSpinBox(self.widget3)
        self.sp_pc_sigma.setDecimals(3)
        self.sp_pc_sigma.setProperty("value", 2.0)
        self.sp_pc_sigma.setObjectName(_fromUtf8("sp_pc_sigma"))
        self.gridLayout_5.addWidget(self.sp_pc_sigma, 1, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.widget3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 1, 3, 1, 1)
        self.cb_pc_alg = QtGui.QComboBox(self.widget3)
        self.cb_pc_alg.setObjectName(_fromUtf8("cb_pc_alg"))
        self.cb_pc_alg.addItem(_fromUtf8(""))
        self.cb_pc_alg.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cb_pc_alg, 1, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.widget3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 2, 1, 1, 1)
        self.sp_pc_kernel_n = QtGui.QSpinBox(self.widget3)
        self.sp_pc_kernel_n.setProperty("value", 32)
        self.sp_pc_kernel_n.setObjectName(_fromUtf8("sp_pc_kernel_n"))
        self.gridLayout_5.addWidget(self.sp_pc_kernel_n, 1, 6, 1, 1)
        self.ck_position_correction_flag = QtGui.QCheckBox(self.widget3)
        self.ck_position_correction_flag.setObjectName(_fromUtf8("ck_position_correction_flag"))
        self.gridLayout_5.addWidget(self.ck_position_correction_flag, 2, 0, 1, 1)
        self.sp_position_correction_start = QtGui.QSpinBox(self.widget3)
        self.sp_position_correction_start.setProperty("value", 50)
        self.sp_position_correction_start.setObjectName(_fromUtf8("sp_position_correction_start"))
        self.gridLayout_5.addWidget(self.sp_position_correction_start, 2, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.widget3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 2, 3, 1, 1)
        self.sp_position_correction_step = QtGui.QSpinBox(self.widget3)
        self.sp_position_correction_step.setProperty("value", 10)
        self.sp_position_correction_step.setObjectName(_fromUtf8("sp_position_correction_step"))
        self.gridLayout_5.addWidget(self.sp_position_correction_step, 2, 4, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 170, 211, 81))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 0, 0, 1, 1)
        self.sp_start_update_probe = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.sp_start_update_probe.setObjectName(_fromUtf8("sp_start_update_probe"))
        self.gridLayout_3.addWidget(self.sp_start_update_probe, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 1, 0, 1, 1)
        self.sp_start_update_object = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.sp_start_update_object.setObjectName(_fromUtf8("sp_start_update_object"))
        self.gridLayout_3.addWidget(self.sp_start_update_object, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.console_info = QtGui.QTextEdit(self.groupBox_6)
        self.console_info.setGeometry(QtCore.QRect(20, 690, 641, 121))
        self.console_info.setReadOnly(True)
        self.console_info.setObjectName(_fromUtf8("console_info"))
        self.recon_bar = QtGui.QProgressBar(self.groupBox_6)
        self.recon_bar.setGeometry(QtCore.QRect(20, 820, 641, 23))
        self.recon_bar.setProperty("value", 0)
        self.recon_bar.setObjectName(_fromUtf8("recon_bar"))
        self.widget4 = QtGui.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label.raise_()
        self.le_scan_num.raise_()
        self.label_7.raise_()
        self.sp_ccd_pixel_um.raise_()
        self.label_31.raise_()
        self.sp_processes.raise_()
        self.label_7.raise_()
        self.ck_bragg_flag.raise_()
        self.ck_pc_flag.raise_()
        self.ck_bragg_flag.raise_()
        self.label_12.raise_()
        self.sp_bragg_theta.raise_()
        self.label_13.raise_()
        self.sp_bragg_gamma.raise_()
        self.label_14.raise_()
        self.sp_bragg_delta.raise_()
        self.btn_recon_start.raise_()
        self.btn_recon_stop.raise_()
        self.groupBox_6.raise_()
        self.ck_gpu_flag.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Data", None))
        self.label.setText(_translate("MainWindow", "Scan number", None))
        self.le_scan_num.setText(_translate("MainWindow", "34784", None))
        self.pushButton.setText(_translate("MainWindow", "View data frame", None))
        self.cb_detectorkind.setItemText(0, _translate("MainWindow", "merlin1", None))
        self.cb_detectorkind.setItemText(1, _translate("MainWindow", "merlin2", None))
        self.cb_detectorkind.setItemText(2, _translate("MainWindow", "timepix1", None))
        self.cb_detectorkind.setItemText(3, _translate("MainWindow", "timepix2", None))
        self.label_36.setText(_translate("MainWindow", "Frame #", None))
        self.cb_dataloader.setItemText(0, _translate("MainWindow", "Load from databroker", None))
        self.cb_dataloader.setItemText(1, _translate("MainWindow", "Load from h5", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Experimental parameters", None))
        self.label_37.setText(_translate("MainWindow", "X-ray energy (keV)", None))
        self.label_42.setText(_translate("MainWindow", "Y step size (nm)", None))
        self.label_38.setText(_translate("MainWindow", "Detector distance (m)", None))
        self.label_40.setText(_translate("MainWindow", "Y array size", None))
        self.label_41.setText(_translate("MainWindow", "X step size (nm)", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "mesh", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "spiral", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "fly", None))
        self.label_46.setText(_translate("MainWindow", "Numbers of points", None))
        self.label_44.setText(_translate("MainWindow", "Y scan range (um)", None))
        self.label_39.setText(_translate("MainWindow", "X array size", None))
        self.label_43.setText(_translate("MainWindow", "X scan range (um)", None))
        self.label_45.setText(_translate("MainWindow", "Scan type: ", None))
        self.label_3.setText(_translate("MainWindow", "Num. of iteration", None))
        self.label_8.setText(_translate("MainWindow", "Algorithm", None))
        self.cb_alg_flag.setItemText(0, _translate("MainWindow", "DM", None))
        self.cb_alg_flag.setItemText(1, _translate("MainWindow", "ML", None))
        self.cb_alg_flag.setItemText(2, _translate("MainWindow", "ER", None))
        self.cb_alg2_flag.setItemText(0, _translate("MainWindow", "DM", None))
        self.cb_alg2_flag.setItemText(1, _translate("MainWindow", "ML", None))
        self.cb_alg2_flag.setItemText(2, _translate("MainWindow", "ER", None))
        self.pushButton_2.setText(_translate("MainWindow", "Load probe", None))
        self.label_9.setText(_translate("MainWindow", "Probe initialization:", None))
        self.checkBox.setText(_translate("MainWindow", "Estimate from data", None))
        self.label_11.setText(_translate("MainWindow", "Object initialization:", None))
        self.checkBox_2.setText(_translate("MainWindow", "Random start", None))
        self.pushButton_3.setText(_translate("MainWindow", "Load object", None))
        self.ck_multislice_flag.setText(_translate("MainWindow", "Multi-slice", None))
        self.label_47.setText(_translate("MainWindow", "Num. of slices", None))
        self.label_48.setText(_translate("MainWindow", "Slice spacing (um)", None))
        self.ck_save_tmp_pic_flag.setText(_translate("MainWindow", "Modes:", None))
        self.label_22.setText(_translate("MainWindow", "Num. of probe mode", None))
        self.label_23.setText(_translate("MainWindow", "Num. of object mode", None))
        self.label_15.setText(_translate("MainWindow", "Amplitude range:", None))
        self.label_33.setText(_translate("MainWindow", "max", None))
        self.label_32.setText(_translate("MainWindow", "min", None))
        self.label_16.setText(_translate("MainWindow", "Phase range:", None))
        self.label_34.setText(_translate("MainWindow", "min", None))
        self.label_35.setText(_translate("MainWindow", "max", None))
        self.ck_gpu_flag.setText(_translate("MainWindow", "GPU:", None))
        self.pushButton_4.setText(_translate("MainWindow", "1", None))
        self.pushButton_5.setText(_translate("MainWindow", "2", None))
        self.pushButton_6.setText(_translate("MainWindow", "3", None))
        self.pushButton_7.setText(_translate("MainWindow", "4", None))
        self.btn_recon_start.setText(_translate("MainWindow", "start", None))
        self.btn_recon_stop.setText(_translate("MainWindow", "stop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Reconstruction parameters", None))
        self.label_7.setText(_translate("MainWindow", "Detector pixel size (um)", None))
        self.label_31.setText(_translate("MainWindow", "Processes", None))
        self.label_2.setText(_translate("MainWindow", "Save filename", None))
        self.le_sign.setText(_translate("MainWindow", "t1", None))
        self.ck_p_flag.setText(_translate("MainWindow", "Use probe", None))
        self.label_4.setText(_translate("MainWindow", "distance", None))
        self.label_10.setText(_translate("MainWindow", "ML", None))
        self.cb_ml_mode.setItemText(0, _translate("MainWindow", "Poisson", None))
        self.label_30.setText(_translate("MainWindow", "DM ver.", None))
        self.label_20.setText(_translate("MainWindow", "alpha (1e-8)", None))
        self.label_21.setText(_translate("MainWindow", "beta", None))
        self.ck_init_obj_flag.setText(_translate("MainWindow", "init. object", None))
        self.ck_init_obj_dpc_flag.setText(_translate("MainWindow", "init. object (dpc)", None))
        self.ck_init_prb_flag.setText(_translate("MainWindow", "init. probe", None))
        self.ck_mask_prb_flag.setText(_translate("MainWindow", "mask probe", None))
        self.ck_prb_center_flag.setText(_translate("MainWindow", "probe center", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Advanced options", None))
        self.ck_mesh_flag.setText(_translate("MainWindow", "mesh", None))
        self.ck_cal_scal_pattern_flag.setText(_translate("MainWindow", "scan pattern", None))
        self.ck_sf_flag.setText(_translate("MainWindow", "sf", None))
        self.ck_ms_pie_flag.setText(_translate("MainWindow", "ms pie", None))
        self.ck_weak_obj_flag.setText(_translate("MainWindow", "weak object", None))
        self.label_5.setText(_translate("MainWindow", "start ave", None))
        self.label_6.setText(_translate("MainWindow", "nth", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Etc", None))
        self.label_12.setText(_translate("MainWindow", "Theta", None))
        self.ck_bragg_flag.setText(_translate("MainWindow", "Bragg: ", None))
        self.label_19.setText(_translate("MainWindow", "Num. kernels", None))
        self.label_13.setText(_translate("MainWindow", "Gamma", None))
        self.label_14.setText(_translate("MainWindow", "Delta", None))
        self.ck_pc_flag.setText(_translate("MainWindow", "Partial coherence:", None))
        self.label_17.setText(_translate("MainWindow", "Sigma", None))
        self.label_18.setText(_translate("MainWindow", "Algorithm", None))
        self.cb_pc_alg.setItemText(0, _translate("MainWindow", "lucy", None))
        self.cb_pc_alg.setItemText(1, _translate("MainWindow", "wiener", None))
        self.label_24.setText(_translate("MainWindow", "Start", None))
        self.ck_position_correction_flag.setText(_translate("MainWindow", "Position correction:", None))
        self.label_25.setText(_translate("MainWindow", "Step", None))
        self.label_28.setText(_translate("MainWindow", "Start update probe", None))
        self.label_29.setText(_translate("MainWindow", "Start update object", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Etc 2", None))

