# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dpc.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(754, 818)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 0, 721, 108))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.groupBox_7)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.le_scan_num = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_scan_num.sizePolicy().hasHeightForWidth())
        self.le_scan_num.setSizePolicy(sizePolicy)
        self.le_scan_num.setMaximumSize(QtCore.QSize(80, 16777215))
        self.le_scan_num.setObjectName(_fromUtf8("le_scan_num"))
        self.gridLayout_4.addWidget(self.le_scan_num, 0, 1, 1, 1)
        self.btn_choose_cwd = QtGui.QPushButton(self.groupBox_7)
        self.btn_choose_cwd.setObjectName(_fromUtf8("btn_choose_cwd"))
        self.gridLayout_4.addWidget(self.btn_choose_cwd, 0, 3, 1, 2)
        self.cb_dataloader = QtGui.QComboBox(self.groupBox_7)
        self.cb_dataloader.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_dataloader.setObjectName(_fromUtf8("cb_dataloader"))
        self.cb_dataloader.addItem(_fromUtf8(""))
        self.cb_dataloader.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cb_dataloader, 1, 0, 1, 2)
        self.btn_load_scan = QtGui.QPushButton(self.groupBox_7)
        self.btn_load_scan.setObjectName(_fromUtf8("btn_load_scan"))
        self.gridLayout_4.addWidget(self.btn_load_scan, 1, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_7)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 1, 3, 1, 1)
        self.cb_detectorkind = QtGui.QComboBox(self.groupBox_7)
        self.cb_detectorkind.setObjectName(_fromUtf8("cb_detectorkind"))
        self.cb_detectorkind.addItem(_fromUtf8(""))
        self.cb_detectorkind.addItem(_fromUtf8(""))
        self.cb_detectorkind.addItem(_fromUtf8(""))
        self.cb_detectorkind.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cb_detectorkind, 1, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_7)
        self.label_36.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_4.addWidget(self.label_36, 1, 5, 1, 1)
        self.sp_fram_num = QtGui.QSpinBox(self.groupBox_7)
        self.sp_fram_num.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sp_fram_num.setMaximum(1000000)
        self.sp_fram_num.setObjectName(_fromUtf8("sp_fram_num"))
        self.gridLayout_4.addWidget(self.sp_fram_num, 1, 6, 1, 1)
        self.btn_view_frame = QtGui.QPushButton(self.groupBox_7)
        self.btn_view_frame.setMinimumSize(QtCore.QSize(121, 0))
        self.btn_view_frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_view_frame.setObjectName(_fromUtf8("btn_view_frame"))
        self.gridLayout_4.addWidget(self.btn_view_frame, 1, 7, 1, 1)
        self.le_working_directory = QtGui.QLineEdit(self.groupBox_7)
        self.le_working_directory.setObjectName(_fromUtf8("le_working_directory"))
        self.gridLayout_4.addWidget(self.le_working_directory, 0, 5, 1, 3)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(50, 110, 641, 191))
        self.groupBox_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.groupBox_8)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(19, 30, 601, 165))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_37 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_9.addWidget(self.label_37, 0, 0, 1, 1)
        self.sp_xray_energy = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.sp_xray_energy.setDecimals(10)
        self.sp_xray_energy.setObjectName(_fromUtf8("sp_xray_energy"))
        self.gridLayout_9.addWidget(self.sp_xray_energy, 0, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_9.addWidget(self.label_42, 2, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_9.addWidget(self.label_38, 0, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_9.addWidget(self.label_40, 1, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_9.addWidget(self.label_41, 2, 0, 1, 1)
        self.sp_x_scan_range = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.sp_x_scan_range.setDecimals(4)
        self.sp_x_scan_range.setObjectName(_fromUtf8("sp_x_scan_range"))
        self.gridLayout_9.addWidget(self.sp_x_scan_range, 3, 1, 1, 1)
        self.cb_scan_type = QtGui.QComboBox(self.gridLayoutWidget_8)
        self.cb_scan_type.setObjectName(_fromUtf8("cb_scan_type"))
        self.cb_scan_type.addItem(_fromUtf8(""))
        self.cb_scan_type.addItem(_fromUtf8(""))
        self.cb_scan_type.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cb_scan_type, 4, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_9.addWidget(self.label_46, 4, 2, 1, 1)
        self.sp_y_scan_range = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.sp_y_scan_range.setDecimals(4)
        self.sp_y_scan_range.setObjectName(_fromUtf8("sp_y_scan_range"))
        self.gridLayout_9.addWidget(self.sp_y_scan_range, 3, 3, 1, 1)
        self.sp_y_step_size = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.sp_y_step_size.setDecimals(4)
        self.sp_y_step_size.setObjectName(_fromUtf8("sp_y_step_size"))
        self.gridLayout_9.addWidget(self.sp_y_step_size, 2, 3, 1, 1)
        self.label_44 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_9.addWidget(self.label_44, 3, 2, 1, 1)
        self.sp_num_points = QtGui.QSpinBox(self.gridLayoutWidget_8)
        self.sp_num_points.setMaximum(1000000)
        self.sp_num_points.setObjectName(_fromUtf8("sp_num_points"))
        self.gridLayout_9.addWidget(self.sp_num_points, 4, 3, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_9.addWidget(self.label_39, 1, 0, 1, 1)
        self.sp_detector_distance = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.sp_detector_distance.setDecimals(4)
        self.sp_detector_distance.setObjectName(_fromUtf8("sp_detector_distance"))
        self.gridLayout_9.addWidget(self.sp_detector_distance, 0, 3, 1, 1)
        self.sp_x_step_size = QtGui.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.sp_x_step_size.setDecimals(4)
        self.sp_x_step_size.setObjectName(_fromUtf8("sp_x_step_size"))
        self.gridLayout_9.addWidget(self.sp_x_step_size, 2, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_9.addWidget(self.label_43, 3, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_9.addWidget(self.label_45, 4, 0, 1, 1)
        self.sp_x_arr_size = QtGui.QSpinBox(self.gridLayoutWidget_8)
        self.sp_x_arr_size.setMaximum(1000000)
        self.sp_x_arr_size.setObjectName(_fromUtf8("sp_x_arr_size"))
        self.gridLayout_9.addWidget(self.sp_x_arr_size, 1, 1, 1, 1)
        self.sp_y_arr_size = QtGui.QSpinBox(self.gridLayoutWidget_8)
        self.sp_y_arr_size.setMaximum(1000000)
        self.sp_y_arr_size.setObjectName(_fromUtf8("sp_y_arr_size"))
        self.gridLayout_9.addWidget(self.sp_y_arr_size, 1, 3, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.groupBox_6)
        self.tabWidget.setGeometry(QtCore.QRect(18, 310, 700, 351))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.sp_n_iterations = QtGui.QSpinBox(self.tab)
        self.sp_n_iterations.setMinimum(1)
        self.sp_n_iterations.setMaximum(999999)
        self.sp_n_iterations.setProperty("value", 50)
        self.sp_n_iterations.setObjectName(_fromUtf8("sp_n_iterations"))
        self.horizontalLayout_4.addWidget(self.sp_n_iterations)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.cb_alg_flag = QtGui.QComboBox(self.tab)
        self.cb_alg_flag.setObjectName(_fromUtf8("cb_alg_flag"))
        self.cb_alg_flag.addItem(_fromUtf8(""))
        self.cb_alg_flag.addItem(_fromUtf8(""))
        self.cb_alg_flag.addItem(_fromUtf8(""))
        self.cb_alg_flag.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cb_alg_flag)
        self.cb_alg2_flag = QtGui.QComboBox(self.tab)
        self.cb_alg2_flag.setObjectName(_fromUtf8("cb_alg2_flag"))
        self.cb_alg2_flag.addItem(_fromUtf8(""))
        self.cb_alg2_flag.addItem(_fromUtf8(""))
        self.cb_alg2_flag.addItem(_fromUtf8(""))
        self.cb_alg2_flag.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cb_alg2_flag)
        self.sp_alg_percentage = QtGui.QDoubleSpinBox(self.tab)
        self.sp_alg_percentage.setProperty("value", 0.8)
        self.sp_alg_percentage.setObjectName(_fromUtf8("sp_alg_percentage"))
        self.horizontalLayout_4.addWidget(self.sp_alg_percentage)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_27 = QtGui.QLabel(self.tab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 0, 0, 1, 1)
        self.le_sign = QtGui.QLineEdit(self.tab)
        self.le_sign.setObjectName(_fromUtf8("le_sign"))
        self.gridLayout.addWidget(self.le_sign, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.le_prb_path = QtGui.QLineEdit(self.tab)
        self.le_prb_path.setReadOnly(True)
        self.le_prb_path.setObjectName(_fromUtf8("le_prb_path"))
        self.gridLayout_10.addWidget(self.le_prb_path, 0, 3, 1, 1)
        self.btn_load_object = QtGui.QPushButton(self.tab)
        self.btn_load_object.setObjectName(_fromUtf8("btn_load_object"))
        self.gridLayout_10.addWidget(self.btn_load_object, 1, 2, 1, 1)
        self.btn_load_probe = QtGui.QPushButton(self.tab)
        self.btn_load_probe.setObjectName(_fromUtf8("btn_load_probe"))
        self.gridLayout_10.addWidget(self.btn_load_probe, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.le_obj_path = QtGui.QLineEdit(self.tab)
        self.le_obj_path.setReadOnly(True)
        self.le_obj_path.setObjectName(_fromUtf8("le_obj_path"))
        self.gridLayout_10.addWidget(self.le_obj_path, 1, 3, 1, 1)
        self.ck_init_prb_flag = QtGui.QCheckBox(self.tab)
        self.ck_init_prb_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_init_prb_flag.setChecked(True)
        self.ck_init_prb_flag.setObjectName(_fromUtf8("ck_init_prb_flag"))
        self.gridLayout_10.addWidget(self.ck_init_prb_flag, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_10.addWidget(self.label_11, 1, 0, 1, 1)
        self.ck_init_obj_flag = QtGui.QCheckBox(self.tab)
        self.ck_init_obj_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_init_obj_flag.setChecked(True)
        self.ck_init_obj_flag.setObjectName(_fromUtf8("ck_init_obj_flag"))
        self.gridLayout_10.addWidget(self.ck_init_obj_flag, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.ck_multislice_flag = QtGui.QCheckBox(self.tab)
        self.ck_multislice_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_multislice_flag.setObjectName(_fromUtf8("ck_multislice_flag"))
        self.gridLayout_11.addWidget(self.ck_multislice_flag, 1, 0, 1, 1)
        self.sp_slice_num = QtGui.QSpinBox(self.tab)
        self.sp_slice_num.setEnabled(False)
        self.sp_slice_num.setProperty("value", 2)
        self.sp_slice_num.setObjectName(_fromUtf8("sp_slice_num"))
        self.gridLayout_11.addWidget(self.sp_slice_num, 1, 3, 1, 1)
        self.label_48 = QtGui.QLabel(self.tab)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_11.addWidget(self.label_48, 1, 4, 1, 1)
        self.sp_slice_spacing_m = QtGui.QDoubleSpinBox(self.tab)
        self.sp_slice_spacing_m.setEnabled(False)
        self.sp_slice_spacing_m.setProperty("value", 5.0)
        self.sp_slice_spacing_m.setObjectName(_fromUtf8("sp_slice_spacing_m"))
        self.gridLayout_11.addWidget(self.sp_slice_spacing_m, 1, 6, 1, 1)
        self.sp_prb_mode_num = QtGui.QSpinBox(self.tab)
        self.sp_prb_mode_num.setEnabled(False)
        self.sp_prb_mode_num.setProperty("value", 5)
        self.sp_prb_mode_num.setObjectName(_fromUtf8("sp_prb_mode_num"))
        self.gridLayout_11.addWidget(self.sp_prb_mode_num, 0, 3, 1, 1)
        self.ck_mode_flag = QtGui.QCheckBox(self.tab)
        self.ck_mode_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_mode_flag.setObjectName(_fromUtf8("ck_mode_flag"))
        self.gridLayout_11.addWidget(self.ck_mode_flag, 0, 0, 1, 1)
        self.sp_obj_mode_num = QtGui.QSpinBox(self.tab)
        self.sp_obj_mode_num.setEnabled(False)
        self.sp_obj_mode_num.setProperty("value", 1)
        self.sp_obj_mode_num.setObjectName(_fromUtf8("sp_obj_mode_num"))
        self.gridLayout_11.addWidget(self.sp_obj_mode_num, 0, 6, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_11.addWidget(self.label_22, 0, 1, 1, 2)
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_11.addWidget(self.label_23, 0, 4, 1, 2)
        self.label_47 = QtGui.QLabel(self.tab)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_11.addWidget(self.label_47, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.sp_amp_min = QtGui.QDoubleSpinBox(self.tab)
        self.sp_amp_min.setPrefix(_fromUtf8(""))
        self.sp_amp_min.setDecimals(3)
        self.sp_amp_min.setProperty("value", 0.85)
        self.sp_amp_min.setObjectName(_fromUtf8("sp_amp_min"))
        self.gridLayout_12.addWidget(self.sp_amp_min, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_12.addWidget(self.label_33, 0, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_12.addWidget(self.label_32, 0, 1, 1, 1)
        self.sp_amp_max = QtGui.QDoubleSpinBox(self.tab)
        self.sp_amp_max.setPrefix(_fromUtf8(""))
        self.sp_amp_max.setDecimals(3)
        self.sp_amp_max.setMinimum(-3.0)
        self.sp_amp_max.setProperty("value", 1.0)
        self.sp_amp_max.setObjectName(_fromUtf8("sp_amp_max"))
        self.gridLayout_12.addWidget(self.sp_amp_max, 0, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_12.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_12.addWidget(self.label_34, 1, 1, 1, 1)
        self.sp_pha_min = QtGui.QDoubleSpinBox(self.tab)
        self.sp_pha_min.setPrefix(_fromUtf8(""))
        self.sp_pha_min.setDecimals(3)
        self.sp_pha_min.setMinimum(-99.0)
        self.sp_pha_min.setProperty("value", -0.6)
        self.sp_pha_min.setObjectName(_fromUtf8("sp_pha_min"))
        self.gridLayout_12.addWidget(self.sp_pha_min, 1, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_12.addWidget(self.label_35, 1, 3, 1, 1)
        self.sp_pha_max = QtGui.QDoubleSpinBox(self.tab)
        self.sp_pha_max.setPrefix(_fromUtf8(""))
        self.sp_pha_max.setDecimals(3)
        self.sp_pha_max.setProperty("value", 0.01)
        self.sp_pha_max.setObjectName(_fromUtf8("sp_pha_max"))
        self.gridLayout_12.addWidget(self.sp_pha_max, 1, 4, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_12)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ck_gpu_flag = QtGui.QCheckBox(self.tab)
        self.ck_gpu_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_gpu_flag.setChecked(True)
        self.ck_gpu_flag.setObjectName(_fromUtf8("ck_gpu_flag"))
        self.horizontalLayout_5.addWidget(self.ck_gpu_flag)
        self.btn_gpu_0 = QtGui.QPushButton(self.tab)
        self.btn_gpu_0.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_gpu_0.setCheckable(True)
        self.btn_gpu_0.setChecked(True)
        self.btn_gpu_0.setObjectName(_fromUtf8("btn_gpu_0"))
        self.horizontalLayout_5.addWidget(self.btn_gpu_0)
        self.btn_gpu_1 = QtGui.QPushButton(self.tab)
        self.btn_gpu_1.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_gpu_1.setCheckable(True)
        self.btn_gpu_1.setChecked(True)
        self.btn_gpu_1.setObjectName(_fromUtf8("btn_gpu_1"))
        self.horizontalLayout_5.addWidget(self.btn_gpu_1)
        self.btn_gpu_2 = QtGui.QPushButton(self.tab)
        self.btn_gpu_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_gpu_2.setCheckable(True)
        self.btn_gpu_2.setChecked(True)
        self.btn_gpu_2.setObjectName(_fromUtf8("btn_gpu_2"))
        self.horizontalLayout_5.addWidget(self.btn_gpu_2)
        self.btn_gpu_3 = QtGui.QPushButton(self.tab)
        self.btn_gpu_3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_gpu_3.setCheckable(True)
        self.btn_gpu_3.setChecked(True)
        self.btn_gpu_3.setObjectName(_fromUtf8("btn_gpu_3"))
        self.horizontalLayout_5.addWidget(self.btn_gpu_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btn_recon_start = QtGui.QPushButton(self.tab)
        self.btn_recon_start.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_recon_start.setObjectName(_fromUtf8("btn_recon_start"))
        self.horizontalLayout_6.addWidget(self.btn_recon_start)
        self.btn_recon_stop = QtGui.QPushButton(self.tab)
        self.btn_recon_stop.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_recon_stop.setObjectName(_fromUtf8("btn_recon_stop"))
        self.horizontalLayout_6.addWidget(self.btn_recon_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 150, 625, 99))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_17 = QtGui.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 1, 1, 1, 1)
        self.ck_pc_flag = QtGui.QCheckBox(self.layoutWidget_2)
        self.ck_pc_flag.setObjectName(_fromUtf8("ck_pc_flag"))
        self.gridLayout_5.addWidget(self.ck_pc_flag, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 5, 1, 1)
        self.sp_bragg_delta = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.sp_bragg_delta.setDecimals(3)
        self.sp_bragg_delta.setProperty("value", 15.46)
        self.sp_bragg_delta.setObjectName(_fromUtf8("sp_bragg_delta"))
        self.gridLayout_5.addWidget(self.sp_bragg_delta, 0, 6, 1, 1)
        self.sp_pc_kernel_n = QtGui.QSpinBox(self.layoutWidget_2)
        self.sp_pc_kernel_n.setProperty("value", 32)
        self.sp_pc_kernel_n.setObjectName(_fromUtf8("sp_pc_kernel_n"))
        self.gridLayout_5.addWidget(self.sp_pc_kernel_n, 1, 6, 1, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 2, 1, 1, 1)
        self.sp_bragg_theta = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.sp_bragg_theta.setDecimals(3)
        self.sp_bragg_theta.setProperty("value", 69.41)
        self.sp_bragg_theta.setObjectName(_fromUtf8("sp_bragg_theta"))
        self.gridLayout_5.addWidget(self.sp_bragg_theta, 0, 2, 1, 1)
        self.sp_pc_sigma = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.sp_pc_sigma.setDecimals(3)
        self.sp_pc_sigma.setProperty("value", 2.0)
        self.sp_pc_sigma.setObjectName(_fromUtf8("sp_pc_sigma"))
        self.gridLayout_5.addWidget(self.sp_pc_sigma, 1, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 1, 3, 1, 1)
        self.cb_pc_alg = QtGui.QComboBox(self.layoutWidget_2)
        self.cb_pc_alg.setObjectName(_fromUtf8("cb_pc_alg"))
        self.cb_pc_alg.addItem(_fromUtf8(""))
        self.cb_pc_alg.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cb_pc_alg, 1, 4, 1, 1)
        self.sp_bragg_gamma = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.sp_bragg_gamma.setDecimals(3)
        self.sp_bragg_gamma.setProperty("value", 33.4)
        self.sp_bragg_gamma.setObjectName(_fromUtf8("sp_bragg_gamma"))
        self.gridLayout_5.addWidget(self.sp_bragg_gamma, 0, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 1, 5, 1, 1)
        self.ck_bragg_flag = QtGui.QCheckBox(self.layoutWidget_2)
        self.ck_bragg_flag.setObjectName(_fromUtf8("ck_bragg_flag"))
        self.gridLayout_5.addWidget(self.ck_bragg_flag, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 0, 1, 1, 1)
        self.ck_position_correction_flag = QtGui.QCheckBox(self.layoutWidget_2)
        self.ck_position_correction_flag.setObjectName(_fromUtf8("ck_position_correction_flag"))
        self.gridLayout_5.addWidget(self.ck_position_correction_flag, 2, 0, 1, 1)
        self.sp_position_correction_start = QtGui.QSpinBox(self.layoutWidget_2)
        self.sp_position_correction_start.setProperty("value", 50)
        self.sp_position_correction_start.setObjectName(_fromUtf8("sp_position_correction_start"))
        self.gridLayout_5.addWidget(self.sp_position_correction_start, 2, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 2, 3, 1, 1)
        self.sp_position_correction_step = QtGui.QSpinBox(self.layoutWidget_2)
        self.sp_position_correction_step.setProperty("value", 10)
        self.sp_position_correction_step.setObjectName(_fromUtf8("sp_position_correction_step"))
        self.gridLayout_5.addWidget(self.sp_position_correction_step, 2, 4, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 131))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sp_ccd_pixel_um = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.sp_ccd_pixel_um.setDecimals(3)
        self.sp_ccd_pixel_um.setProperty("value", 55.0)
        self.sp_ccd_pixel_um.setObjectName(_fromUtf8("sp_ccd_pixel_um"))
        self.gridLayout_3.addWidget(self.sp_ccd_pixel_um, 0, 4, 1, 2)
        self.sp_distance = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.sp_distance.setDecimals(3)
        self.sp_distance.setMaximum(999999.999)
        self.sp_distance.setObjectName(_fromUtf8("sp_distance"))
        self.gridLayout_3.addWidget(self.sp_distance, 1, 4, 1, 2)
        self.label_50 = QtGui.QLabel(self.layoutWidget)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_3.addWidget(self.label_50, 2, 3, 1, 2)
        self.sp_start_ave = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.sp_start_ave.setDecimals(1)
        self.sp_start_ave.setProperty("value", 0.8)
        self.sp_start_ave.setObjectName(_fromUtf8("sp_start_ave"))
        self.gridLayout_3.addWidget(self.sp_start_ave, 3, 5, 1, 1)
        self.sp_x_direction = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.sp_x_direction.setDecimals(1)
        self.sp_x_direction.setMinimum(-1.0)
        self.sp_x_direction.setMaximum(1.0)
        self.sp_x_direction.setSingleStep(0.1)
        self.sp_x_direction.setProperty("value", -1.0)
        self.sp_x_direction.setObjectName(_fromUtf8("sp_x_direction"))
        self.gridLayout_3.addWidget(self.sp_x_direction, 2, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_3.addWidget(self.label_49, 2, 0, 1, 2)
        self.sp_y_direction = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.sp_y_direction.setDecimals(1)
        self.sp_y_direction.setMinimum(-1.0)
        self.sp_y_direction.setMaximum(1.0)
        self.sp_y_direction.setSingleStep(0.1)
        self.sp_y_direction.setProperty("value", -1.0)
        self.sp_y_direction.setObjectName(_fromUtf8("sp_y_direction"))
        self.gridLayout_3.addWidget(self.sp_y_direction, 2, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 4)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 4)
        self.ck_angle_correction_flag = QtGui.QCheckBox(self.layoutWidget)
        self.ck_angle_correction_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_angle_correction_flag.setObjectName(_fromUtf8("ck_angle_correction_flag"))
        self.gridLayout_3.addWidget(self.ck_angle_correction_flag, 3, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 3, 1, 2)
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(356, 13, 317, 61))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_28 = QtGui.QLabel(self.layoutWidget1)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_7.addWidget(self.label_28, 0, 0, 1, 1)
        self.sp_start_update_probe = QtGui.QSpinBox(self.layoutWidget1)
        self.sp_start_update_probe.setObjectName(_fromUtf8("sp_start_update_probe"))
        self.gridLayout_7.addWidget(self.sp_start_update_probe, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 0, 2, 1, 1)
        self.cb_ml_mode = QtGui.QComboBox(self.layoutWidget1)
        self.cb_ml_mode.setObjectName(_fromUtf8("cb_ml_mode"))
        self.cb_ml_mode.addItem(_fromUtf8(""))
        self.cb_ml_mode.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cb_ml_mode, 0, 3, 1, 2)
        self.label_29 = QtGui.QLabel(self.layoutWidget1)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_7.addWidget(self.label_29, 1, 0, 1, 1)
        self.sp_start_update_object = QtGui.QSpinBox(self.layoutWidget1)
        self.sp_start_update_object.setObjectName(_fromUtf8("sp_start_update_object"))
        self.gridLayout_7.addWidget(self.sp_start_update_object, 1, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_7.addWidget(self.label_30, 1, 2, 1, 2)
        self.sp_dm_version = QtGui.QSpinBox(self.layoutWidget1)
        self.sp_dm_version.setProperty("value", 1)
        self.sp_dm_version.setObjectName(_fromUtf8("sp_dm_version"))
        self.gridLayout_7.addWidget(self.sp_dm_version, 1, 4, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(370, 102, 291, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_15 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.btn_MPI_file = QtGui.QPushButton(self.layoutWidget2)
        self.btn_MPI_file.setObjectName(_fromUtf8("btn_MPI_file"))
        self.gridLayout_15.addWidget(self.btn_MPI_file, 0, 0, 1, 1)
        self.le_MPI_file_path = QtGui.QLineEdit(self.layoutWidget2)
        self.le_MPI_file_path.setObjectName(_fromUtf8("le_MPI_file_path"))
        self.gridLayout_15.addWidget(self.le_MPI_file_path, 0, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 250, 630, 64))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_16 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_31 = QtGui.QLabel(self.layoutWidget3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 1, 3, 1, 1)
        self.sp_display_interval = QtGui.QSpinBox(self.layoutWidget3)
        self.sp_display_interval.setMinimum(1)
        self.sp_display_interval.setObjectName(_fromUtf8("sp_display_interval"))
        self.gridLayout_8.addWidget(self.sp_display_interval, 1, 2, 1, 1)
        self.sp_processes = QtGui.QSpinBox(self.layoutWidget3)
        self.sp_processes.setObjectName(_fromUtf8("sp_processes"))
        self.gridLayout_8.addWidget(self.sp_processes, 1, 4, 1, 1)
        self.sp_beta = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.sp_beta.setDecimals(2)
        self.sp_beta.setMaximum(96.99)
        self.sp_beta.setProperty("value", 0.9)
        self.sp_beta.setObjectName(_fromUtf8("sp_beta"))
        self.gridLayout_8.addWidget(self.sp_beta, 0, 4, 1, 1)
        self.label_55 = QtGui.QLabel(self.layoutWidget3)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_8.addWidget(self.label_55, 1, 0, 1, 2)
        self.label_21 = QtGui.QLabel(self.layoutWidget3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 0, 3, 1, 1)
        self.sp_alpha = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.sp_alpha.setDecimals(2)
        self.sp_alpha.setMaximum(10.0)
        self.sp_alpha.setProperty("value", 1.0)
        self.sp_alpha.setObjectName(_fromUtf8("sp_alpha"))
        self.gridLayout_8.addWidget(self.sp_alpha, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 0, 0, 1, 2)
        self.gridLayout_16.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.ck_init_obj_dpc_flag = QtGui.QCheckBox(self.layoutWidget3)
        self.ck_init_obj_dpc_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_init_obj_dpc_flag.setObjectName(_fromUtf8("ck_init_obj_dpc_flag"))
        self.gridLayout_13.addWidget(self.ck_init_obj_dpc_flag, 0, 0, 1, 1)
        self.ck_mask_prb_flag = QtGui.QCheckBox(self.layoutWidget3)
        self.ck_mask_prb_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_mask_prb_flag.setObjectName(_fromUtf8("ck_mask_prb_flag"))
        self.gridLayout_13.addWidget(self.ck_mask_prb_flag, 0, 1, 1, 1)
        self.ck_prb_center_flag = QtGui.QCheckBox(self.layoutWidget3)
        self.ck_prb_center_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_prb_center_flag.setChecked(True)
        self.ck_prb_center_flag.setObjectName(_fromUtf8("ck_prb_center_flag"))
        self.gridLayout_13.addWidget(self.ck_prb_center_flag, 1, 0, 1, 1)
        self.ck_weak_obj_flag = QtGui.QCheckBox(self.layoutWidget3)
        self.ck_weak_obj_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_weak_obj_flag.setObjectName(_fromUtf8("ck_weak_obj_flag"))
        self.gridLayout_13.addWidget(self.ck_weak_obj_flag, 1, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_13, 0, 1, 1, 1)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.ck_mesh_flag = QtGui.QCheckBox(self.layoutWidget3)
        self.ck_mesh_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_mesh_flag.setChecked(True)
        self.ck_mesh_flag.setObjectName(_fromUtf8("ck_mesh_flag"))
        self.gridLayout_14.addWidget(self.ck_mesh_flag, 0, 0, 1, 1)
        self.ck_ms_pie_flag = QtGui.QCheckBox(self.layoutWidget3)
        self.ck_ms_pie_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_ms_pie_flag.setObjectName(_fromUtf8("ck_ms_pie_flag"))
        self.gridLayout_14.addWidget(self.ck_ms_pie_flag, 1, 0, 1, 1)
        self.ck_sf_flag = QtGui.QCheckBox(self.layoutWidget3)
        self.ck_sf_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_sf_flag.setObjectName(_fromUtf8("ck_sf_flag"))
        self.gridLayout_14.addWidget(self.ck_sf_flag, 2, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_14, 0, 2, 1, 1)
        self.ck_cal_scal_pattern_flag = QtGui.QCheckBox(self.tab_2)
        self.ck_cal_scal_pattern_flag.setGeometry(QtCore.QRect(370, 76, 171, 22))
        self.ck_cal_scal_pattern_flag.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ck_cal_scal_pattern_flag.setObjectName(_fromUtf8("ck_cal_scal_pattern_flag"))
        self.sp_nth = QtGui.QSpinBox(self.tab_2)
        self.sp_nth.setGeometry(QtCore.QRect(589, 76, 48, 22))
        self.sp_nth.setProperty("value", 5)
        self.sp_nth.setObjectName(_fromUtf8("sp_nth"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(561, 76, 20, 22))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.recon_bar = QtGui.QProgressBar(self.groupBox_6)
        self.recon_bar.setGeometry(QtCore.QRect(18, 770, 700, 25))
        self.recon_bar.setProperty("value", 0)
        self.recon_bar.setObjectName(_fromUtf8("recon_bar"))
        self.console_info = QtGui.QTextEdit(self.groupBox_6)
        self.console_info.setGeometry(QtCore.QRect(18, 670, 700, 100))
        self.console_info.setReadOnly(True)
        self.console_info.setObjectName(_fromUtf8("console_info"))
        self.groupBox_7.raise_()
        self.groupBox_8.raise_()
        self.recon_bar.raise_()
        self.console_info.raise_()
        self.tabWidget.raise_()
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NSLS-II HXN Pytchography", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Data", None))
        self.label.setText(_translate("MainWindow", "Scan number", None))
        self.le_scan_num.setText(_translate("MainWindow", "34784", None))
        self.btn_choose_cwd.setText(_translate("MainWindow", "working directory", None))
        self.cb_dataloader.setItemText(0, _translate("MainWindow", "Load from h5", None))
        self.cb_dataloader.setItemText(1, _translate("MainWindow", "Load from databroker", None))
        self.btn_load_scan.setText(_translate("MainWindow", "Load", None))
        self.label_26.setText(_translate("MainWindow", "detector", None))
        self.cb_detectorkind.setItemText(0, _translate("MainWindow", "merlin1", None))
        self.cb_detectorkind.setItemText(1, _translate("MainWindow", "merlin2", None))
        self.cb_detectorkind.setItemText(2, _translate("MainWindow", "timepix1", None))
        self.cb_detectorkind.setItemText(3, _translate("MainWindow", "timepix2", None))
        self.label_36.setText(_translate("MainWindow", "Frame #", None))
        self.btn_view_frame.setText(_translate("MainWindow", "View data frame", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Experimental parameters", None))
        self.label_37.setText(_translate("MainWindow", "X-ray energy (keV)", None))
        self.label_42.setText(_translate("MainWindow", "Y step size (nm)", None))
        self.label_38.setText(_translate("MainWindow", "Detector distance (m)", None))
        self.label_40.setText(_translate("MainWindow", "Y array size", None))
        self.label_41.setText(_translate("MainWindow", "X step size (nm)", None))
        self.cb_scan_type.setItemText(0, _translate("MainWindow", "mesh", None))
        self.cb_scan_type.setItemText(1, _translate("MainWindow", "spiral", None))
        self.cb_scan_type.setItemText(2, _translate("MainWindow", "fly", None))
        self.label_46.setText(_translate("MainWindow", "Numbers of points", None))
        self.label_44.setText(_translate("MainWindow", "Y scan range (um)", None))
        self.label_39.setText(_translate("MainWindow", "X array size", None))
        self.label_43.setText(_translate("MainWindow", "X scan range (um)", None))
        self.label_45.setText(_translate("MainWindow", "Scan type: ", None))
        self.label_3.setText(_translate("MainWindow", "Num. of iteration", None))
        self.label_8.setText(_translate("MainWindow", "Algorithm", None))
        self.cb_alg_flag.setItemText(0, _translate("MainWindow", "DM", None))
        self.cb_alg_flag.setItemText(1, _translate("MainWindow", "ER", None))
        self.cb_alg_flag.setItemText(2, _translate("MainWindow", "ML_G", None))
        self.cb_alg_flag.setItemText(3, _translate("MainWindow", "ML_P", None))
        self.cb_alg2_flag.setItemText(0, _translate("MainWindow", "DM", None))
        self.cb_alg2_flag.setItemText(1, _translate("MainWindow", "ER", None))
        self.cb_alg2_flag.setItemText(2, _translate("MainWindow", "ML_G", None))
        self.cb_alg2_flag.setItemText(3, _translate("MainWindow", "ML_P", None))
        self.label_27.setText(_translate("MainWindow", "Save filename", None))
        self.le_sign.setText(_translate("MainWindow", "t1", None))
        self.btn_load_object.setText(_translate("MainWindow", "Load object", None))
        self.btn_load_probe.setText(_translate("MainWindow", "Load probe", None))
        self.label_9.setText(_translate("MainWindow", "Probe initialization:", None))
        self.ck_init_prb_flag.setText(_translate("MainWindow", "Estimate from data", None))
        self.label_11.setText(_translate("MainWindow", "Object initialization:", None))
        self.ck_init_obj_flag.setText(_translate("MainWindow", "Random start", None))
        self.ck_multislice_flag.setText(_translate("MainWindow", "Multi-slice", None))
        self.label_48.setText(_translate("MainWindow", "Slice spacing (um)", None))
        self.ck_mode_flag.setText(_translate("MainWindow", "Modes:", None))
        self.label_22.setText(_translate("MainWindow", "Num. of probe mode", None))
        self.label_23.setText(_translate("MainWindow", "Num. of object mode", None))
        self.label_47.setText(_translate("MainWindow", "Num. of slices", None))
        self.label_15.setText(_translate("MainWindow", "Amplitude range:", None))
        self.label_33.setText(_translate("MainWindow", "max", None))
        self.label_32.setText(_translate("MainWindow", "min", None))
        self.label_16.setText(_translate("MainWindow", "Phase range:", None))
        self.label_34.setText(_translate("MainWindow", "min", None))
        self.label_35.setText(_translate("MainWindow", "max", None))
        self.ck_gpu_flag.setText(_translate("MainWindow", "GPU:", None))
        self.btn_gpu_0.setText(_translate("MainWindow", "0", None))
        self.btn_gpu_1.setText(_translate("MainWindow", "1", None))
        self.btn_gpu_2.setText(_translate("MainWindow", "2", None))
        self.btn_gpu_3.setText(_translate("MainWindow", "3", None))
        self.btn_recon_start.setText(_translate("MainWindow", "start", None))
        self.btn_recon_stop.setText(_translate("MainWindow", "stop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Reconstruction parameters", None))
        self.label_17.setText(_translate("MainWindow", "Sigma", None))
        self.ck_pc_flag.setText(_translate("MainWindow", "Partial coherence:", None))
        self.label_14.setText(_translate("MainWindow", "Delta", None))
        self.label_24.setText(_translate("MainWindow", "Start", None))
        self.label_18.setText(_translate("MainWindow", "Algorithm", None))
        self.cb_pc_alg.setItemText(0, _translate("MainWindow", "lucy", None))
        self.cb_pc_alg.setItemText(1, _translate("MainWindow", "wiener", None))
        self.label_13.setText(_translate("MainWindow", "Gamma", None))
        self.label_19.setText(_translate("MainWindow", "Num. kernels", None))
        self.ck_bragg_flag.setText(_translate("MainWindow", "Bragg: ", None))
        self.label_12.setText(_translate("MainWindow", "Theta", None))
        self.ck_position_correction_flag.setText(_translate("MainWindow", "Position correction:", None))
        self.label_25.setText(_translate("MainWindow", "Step", None))
        self.label_50.setText(_translate("MainWindow", "y direction", None))
        self.label_49.setText(_translate("MainWindow", "x direction", None))
        self.label_4.setText(_translate("MainWindow", "probe propagation distance (um)", None))
        self.label_7.setText(_translate("MainWindow", "Detector pixel size (um)", None))
        self.ck_angle_correction_flag.setText(_translate("MainWindow", "angular correction", None))
        self.label_5.setText(_translate("MainWindow", "start ave", None))
        self.label_28.setText(_translate("MainWindow", "Start update probe", None))
        self.label_10.setText(_translate("MainWindow", "ML", None))
        self.cb_ml_mode.setItemText(0, _translate("MainWindow", "Poisson", None))
        self.cb_ml_mode.setItemText(1, _translate("MainWindow", "Gaussian", None))
        self.label_29.setText(_translate("MainWindow", "Start update object", None))
        self.label_30.setText(_translate("MainWindow", "DM ver.", None))
        self.btn_MPI_file.setText(_translate("MainWindow", "MPI machine file", None))
        self.label_31.setText(_translate("MainWindow", "Processes", None))
        self.label_55.setText(_translate("MainWindow", "Display interval", None))
        self.label_21.setText(_translate("MainWindow", "beta", None))
        self.label_20.setText(_translate("MainWindow", "alpha (1e-8)", None))
        self.ck_init_obj_dpc_flag.setText(_translate("MainWindow", "init. object (dpc)", None))
        self.ck_mask_prb_flag.setText(_translate("MainWindow", "mask probe", None))
        self.ck_prb_center_flag.setText(_translate("MainWindow", "probe center", None))
        self.ck_weak_obj_flag.setText(_translate("MainWindow", "weak object", None))
        self.ck_mesh_flag.setText(_translate("MainWindow", "mesh", None))
        self.ck_ms_pie_flag.setText(_translate("MainWindow", "ms pie", None))
        self.ck_sf_flag.setText(_translate("MainWindow", "sf", None))
        self.ck_cal_scal_pattern_flag.setText(_translate("MainWindow", "calculate scan pattern", None))
        self.label_6.setText(_translate("MainWindow", "nth", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Advanced options", None))

