# -*- mode: yaml -*-

jobs:
- job: linux
  pool: Default
  timeoutInMinutes: 10
  strategy:
    maxParallel: 1
  steps:
  - script: |
       hostname
       whoami
       pwd
       ls -l
    displayName: Ensure the right machine
  - script: |
       conda create -n _azure_test -c conda-forge -y python=3.7
       source activate _azure_test
       python --version
    displayName: Create Conda environment
  - script: |
       source deactivate _azure_test
       conda env remove -n _azure_test
    displayName: Remove Conda environment
