# -*- mode: yaml -*-

jobs:
- job: linux
  pool: Default
  timeoutInMinutes: 10
  strategy:
    maxParallel: 1
  steps:
  - script: |
       hostname
    displayName: Ensure the right machine
  - script: |
       conda create -n _azure_test -c conda-forge -y python=3.7
       source activate _azure_test
       conda list
       python --version
       conda deactivate
       conda env remove -n _azure_test
    displayName: Test Conda environment
