# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    name: Default
    demands:
    - gpu -equals true
  timeoutInMinutes: 10
  strategy:
    maxParallel: 1
  workspace:
    clean: all
  steps:
  - checkout: self
    submodules: true
  - script: |
       hostname
    displayName: Ensure the right machine
  - script: |
       conda create -n _azure_test -c conda-forge -y python=3.7 \
         pyfftw pyqt=5 numpy scipy matplotlib pillow h5py posix_ipc databroker openmpi mpi4py numba
       source activate _azure_test
       conda list
       python --version
       pip install -v .
       conda deactivate
       conda env remove -n _azure_test
    displayName: Test Conda environment
    #failOnStderr: true  # pip and conda print warnings to stderr...
