# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, gpu]
    
    #runs-on: ubuntu-18.04
    
    #env:
        #GIT_EXEC_PATH: /home/leofang/miniconda3/envs/GH_action_runner/libexec/git-core
      #PATH: /home/leofang/miniconda3/envs/GH_action_runner/bin/:$PATH

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: TEST
      #echo "::add-path::/home/leofang/miniconda3/envs/GH_action_runner/bin/"
      run: |
        echo "path is" $PATH
        which git 
        git --version
        #echo $GIT_EXEC_PATH
        
      #env:
        #GIT_EXEC_PATH: /home/leofang/miniconda3/envs/GH_action_runner/libexec/git-core
        #PATH: /home/leofang/miniconda3/envs/GH_action_runner/bin/:$PATH

    - name: Chekout
      # this has git >= 2.18 installed, needed at the checkout stage
      #run: source activate GH_action_runner

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      
      # this needs git >= 2.18, which is not yet available on the local runner
      with:
        submodules: true
        
      env:
        PATH: /home/leofang/miniconda3/envs/GH_action_runner/bin:/home/leofang/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
        #GIT_EXEC_PATH: /home/leofang/miniconda3/envs/GH_action_runner/libexec/git-core

    # Runs a single command using the runners shell
    - name: Ensure the right machine
      run: hostname

    # Runs a set of commands using the runners shell
    - name: Test Conda environment
      run: |
        pwd
        ls -l
        conda create -n _azure_test -c conda-forge -y python=3.7 \
          pyfftw pyqt=5 numpy scipy matplotlib pillow h5py posix_ipc databroker openmpi mpi4py numba
        source activate _azure_test
        conda list
        python --version
        pip install -v .
        conda deactivate
        conda env remove -n _azure_test
